title = "Coin Coin"
baseURL = "https://coin-coin.xyz/"
copyright = ""

theme = "minimo"

googleAnalytics = "" 
disqusShortname = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = false

# Missing translations will default to this content language
defaultContentLanguage = "en"

enableEmoji = true

[params.info]
description = "Just an another dev blog with black jack and hookers" # Suggested, controls default description meta
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon/favicon.ico"
customCSS = ["css/prism.css"]
customJS = ["js/prism.js", "js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Daniel Chesters"
startYear = "2017"
suffix = """— licensed under a <a rel="license" href="//creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.<br/>Rubber duck favicon/logo made by <a href=
"https://www.freepik.com/home">Freepik</a> from <a href="http://wwww.flaticon.com">www.flaticon.com</a>"""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006-01-02"
listDateFormat = "2006-01-02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideSocialMenu = false
showReadingTime = true
accentColor = "#ff4d00"

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
codepen = ""
email = ""
facebook = ""
github = "DanielChesters"
gitlab = "daniel.chesters"
instagram = ""
linkedin = "daniel-chesters"
twitter = ""

[params.social.config]
platforms = ["linkedin", "github", "gitlab"]
#["github","facebook","twitter","instagram","email","codepen","linkedin"]

[author]
name = "Daniel Chesters"

[taxonomies]
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"


[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

[languages]
  # edit this block for your own language
  [languages.fr]
    lang = "fr"
    languageName = "Français"
    weight = 1
  [[languages.fr.menu.main]]
    url = "/fr/"
    name = "Accueil"
    weight = -99
  [[languages.fr.menu.main]]
    url = "/en/"
    name = "English"
    weight = 99
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 2
  [[languages.en.menu.main]]
    url = "/"
    name = "Home"
    weight = -99
  [[languages.en.menu.main]]
    url = "/fr/"
    name = "Français"
    weight = 99

[params.widgets]
 homepage = ["recent_posts"]
 sidebar = ["about", "taxonomy_cloud"]
 footer = ["social_menu"]

[params.sidebar]
 enable = true
