title = "Coin Coin"
baseURL = "https://coin-coin.xyz/"
copyright = ""

theme = "m10c"

googleAnalytics = "" 
disqusShortname = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true 

# Missing translations will default to this content language
defaultContentLanguage = "en"

enableEmoji = true

[params]
author = "Daniel Chesters"
email = "daniel.chesters@gmail.com"
description = "Just an another dev blog with black jack and hookers"
favicon = "/favicon/favicon.ico"
avatar = "/img/logo.png"

[params.style]
darkestColor = "#242930"
darkColor = "#353b43"
lightColor = "#afbac4"
lightestColor = "#fff"
primaryColor = "#ff4d00"

[[params.social]]
icon = "github"
name = "Github"
url = "https://github.com/danielChesters"

[[params.social]]
icon = "gitlab"
name = "Gitlab"
url = "https://gitlab.com/daniel.chesters"

[[params.social]]
icon = "linkedin"
name = "Linkedin"
url = "https://www.linkedin.com/in/daniel-chesters"

[author]
name = "Daniel Chesters"

[permalinks]
page = "/:slug/"

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

[languages]
  # edit this block for your own language
  [languages.fr]
    lang = "fr"
    languageName = "Français"
    weight = 1
  [[languages.fr.menu.main]]
    url = "/fr/"
    name = "Accueil"
    weight = -99
  [[languages.fr.menu.main]]
    url = "/en/"
    name = "English"
    weight = 99
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 2
  [[languages.en.menu.main]]
    url = "/"
    name = "Home"
    weight = -99
  [[languages.en.menu.main]]
    url = "/fr/"
    name = "Français"
    weight = 99

[mediaTypes]
    [mediaTypes."text/gemini"]
        suffixes = ["gmi"]
    [mediaTypes."application/atom"]
        suffixes = ["xml"]

[outputFormats]
    [outputFormats.GEMINI]
        name = "GEMINI"
        isPlainText = true
        isHTML = false
        mediaType = "text/gemini"
        protocol = "gemini://"
        permalinkable = true
        path = "gemini/"
    [outputFormats.ATOM_GEMINI]
        name = "ATOM_GEMINI"
        isPlainText = false
        isHTML = true
        protocol = "gemini://"
        path = "gemini/"
        permalinkable = true
        mediaType = "application/atom"
        baseName = "atom"

[outputs]
    home = ["HTML", "RSS", "ATOM_GEMINI", "GEMINI"]
    page = ["HTML"]

